# Generated by Django 3.1.8 on 2022-01-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('user', '0003_auto_20220111_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='gentests_history',
        ),
        migrations.AddField(
            model_name='customuser',
            name='gentests_history',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='core.GenTest'),
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='problems_history',
        ),
        migrations.AddField(
            model_name='customuser',
            name='problems_history',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='core.Problem'),
        ),
    ]
