# Generated by Django 3.2 on 2022-02-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('user', '0004_auto_20220111_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gentests_history',
            field=models.ManyToManyField(blank=True, default=None, to='core.GenTest'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='problems_history',
            field=models.ManyToManyField(blank=True, default=None, to='core.Problem'),
        ),
    ]
