# Generated by Django 3.1.8 on 2022-01-11 17:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='title')),
                ('description', models.CharField(max_length=350, unique=True, verbose_name='description')),
                ('achieve_image', models.ImageField(blank=True, null=True, upload_to='achieve_images')),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_description', models.CharField(default='', max_length=1000)),
                ('problem_latex', models.CharField(default='', max_length=1000)),
                ('answer', models.CharField(default='', max_length=1000)),
                ('problem_mmr', models.IntegerField(blank=True, default=0, null=True)),
                ('problem_date_generation', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_name', models.CharField(choices=[('empty', 'empty'), ('bronze', 'bronze'), ('silver', 'silver'), ('gold', 'gold'), ('plat', 'plat'), ('diamond', 'diamond'), ('master', 'master'), ('grand_master', 'grand_master')], default='empty', max_length=30)),
                ('rank_position', models.IntegerField(default=1, unique=True, validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(1)])),
                ('rank_mmr_range_start', models.IntegerField(default=0)),
                ('rank_mmr_range_end', models.IntegerField(default=0)),
                ('rank_image', models.ImageField(blank=True, null=True, upload_to='rank_images')),
            ],
        ),
        migrations.CreateModel(
            name='GenTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=1000)),
                ('difficult', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard'), ('Pro', 'Pro')], default='Easy', max_length=30)),
                ('hours_expected', models.TimeField()),
                ('description', models.CharField(default='', max_length=1000)),
                ('test_date_generation', models.DateField()),
                ('problems', models.ManyToManyField(default=None, to='core.Problem')),
            ],
        ),
    ]
