# Generated by Django 3.2.7 on 2021-09-16 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='title')),
                ('description', models.CharField(max_length=350, unique=True, verbose_name='description')),
                ('achieve_image', models.ImageField(blank=True, null=True, upload_to='achieve_images')),
            ],
        ),
        migrations.CreateModel(
            name='MonthActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_name', models.CharField(choices=[('empty', 'empty'), ('bronze', 'bronze'), ('silver', 'silver'), ('gold', 'gold'), ('plat', 'plat'), ('diamond', 'diamond'), ('master', 'master'), ('grand_master', 'grand_master')], default='empty', max_length=30)),
                ('rank_image', models.ImageField(blank=True, null=True, upload_to='rank_images')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='user_images')),
                ('level_xp', models.IntegerField(blank=True, null=True)),
                ('rank', models.ManyToManyField(blank=True, default=None, to='core.Rank')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
